<a href="https://colab.research.google.com/github/rahiakela/machine-learning-research-and-practice/blob/main/machine-learning-with-python-cookbook/01_working_with_vector_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Setup

In [1]:
import numpy as np

##Pre-allocating NumPy Arrays

In [2]:
# Generate a vector of shape (1,5) containing all zeros
vec = np.zeros(shape=5)
vec

array([0., 0., 0., 0., 0.])

In [3]:
# Generate a matrix of shape (3,3) containing all ones
matrix = np.full(shape=(3, 3), fill_value=1)
matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##Selecting Elements

In [4]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Select third element of vector
vector[2]

3

In [5]:
# Select second row, second column
matrix[1, 1]

5

In [6]:
matrix[1, 2]

6

In [7]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [8]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [9]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [10]:
# Select the last element
vector[-1]

6

In [11]:
# Reverse the vector
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [12]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Select the first two rows and all columns of a matrix
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# Select all rows and the second column
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

In [15]:
matrix[:, 2:3]

array([[3],
       [6],
       [9]])

In [16]:
matrix[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

##Describing a Matrix

In [17]:
# Create matrix
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# View number of rows and columns
matrix.shape

(3, 4)

In [18]:
# View number of elements (rows * columns)
matrix.size

12

In [19]:
# View number of dimensions
matrix.ndim

2

##Applying Functions over Each Element

In [20]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [21]:
# we can create a much simpler version of our solution using broadcasting
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

##Finding Maximum and Minimum Values

In [22]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Return maximum element
np.max(matrix)

9

In [23]:
# Return minimum element
np.min(matrix)

1

In [24]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [25]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

##Calculating Average, Variance, and Standard Deviation