<a href="https://colab.research.google.com/github/rahiakela/machine-learning-research-and-practice/blob/main/machine-learning-with-python-cookbook/01_working_with_vector_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Setup

In [1]:
import numpy as np

##Pre-allocating NumPy Arrays

In [ ]:
# Generate a vector of shape (1,5) containing all zeros
vec = np.zeros(shape=5)
vec

array([0., 0., 0., 0., 0.])

In [ ]:
# Generate a matrix of shape (3,3) containing all ones
matrix = np.full(shape=(3, 3), fill_value=1)
matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##Selecting Elements

In [ ]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Select third element of vector
vector[2]

3

In [ ]:
# Select second row, second column
matrix[1, 1]

5

In [ ]:
matrix[1, 2]

6

In [ ]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [ ]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [ ]:
# Select the last element
vector[-1]

6

In [ ]:
# Reverse the vector
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Select the first two rows and all columns of a matrix
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Select all rows and the second column
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

In [ ]:
matrix[:, 2:3]

array([[3],
       [6],
       [9]])

In [ ]:
matrix[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

##Describing a Matrix

In [ ]:
# Create matrix
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# View number of rows and columns
matrix.shape

(3, 4)

In [ ]:
# View number of elements (rows * columns)
matrix.size

12

In [ ]:
# View number of dimensions
matrix.ndim

2

##Applying Functions over Each Element

In [ ]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
# we can create a much simpler version of our solution using broadcasting
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

##Finding Maximum and Minimum Values

In [ ]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Return maximum element
np.max(matrix)

9

In [ ]:
# Return minimum element
np.min(matrix)

1

In [ ]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [ ]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

##Calculating Average, Variance, and Standard Deviation

In [ ]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# mean
np.mean(matrix)

5.0

In [ ]:
# variance
np.var(matrix)

6.666666666666667

In [ ]:
# standard deviation
np.std(matrix)

2.581988897471611

In [ ]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [ ]:
# Find the mean value in each row
np.mean(matrix, axis=1)

array([2., 5., 8.])

##Reshaping Arrays

In [ ]:
# Create 4x3 matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# 2 row and as many columns as needed
matrix.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# 3 row and as many columns as needed
matrix.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# one row and as many columns as needed
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
# return a one-dimensional array of that length
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

##Transposing

In [ ]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# a vector can’t be transposed because it’s just a collection of values
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [ ]:
# converting a row vector to a column vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

##Flattening Matrix

In [2]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Alternatively, we can use reshape to create a row vector
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [6]:
# Alternatively, we can use reshape to create a column vector
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [7]:
# flattening very large arrays and speeding up code
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_b = np.array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])

# Create a list of matrices
matrix_list = [matrix_a, matrix_b]
# Flatten the entire list of matrices
np.ravel(matrix_list)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 22, 33, 44, 55, 66, 77, 88,
       99])

##Matrix Rank

In [8]:
matrix = np.array([
    [1, 1, 1],
    [1, 1, 10],
    [1, 1, 15]
])

# Return matrix rank
np.linalg.matrix_rank(matrix)

2

##Matrix Diagonal

In [9]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Return diagonal elements
matrix.diagonal()

array([1, 5, 9])

In [10]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [14]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([4, 8])

##Matrix Trace

In [15]:
# Create matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Return trace
matrix.trace()

15

In [16]:
# Return diagonal and sum elements
sum(matrix.diagonal())

15

##Dot Products